# fly.toml app configuration file generated for actes-williamblondel-fr on 2024-01-09T20:20:50+08:00
#
# See https://fly.io/docs/reference/configuration/ for information about how to use this file.
#

app = "actes-williamblondel-fr"
primary_region = "cdg"
kill_signal = "SIGINT"
kill_timeout = "5s"
swap_size_mb = 512

[build]

[http_service]
  internal_port = 80
  force_https = true
  auto_stop_machines = false
  auto_start_machines = true
  min_machines_running = 0
  processes = ["app"]

[[vm]]
  cpu_kind = "shared"
  cpus = 1
  memory_mb = 256
