#!/bin/sh

if [ "$#" -ne 1 ]; then
    echo "Usage: $0 <sqlite_file>"
    exit 1
fi

sqlite_file="$1"

if [ ! -f "$sqlite_file" ]; then
    echo "File not found: $sqlite_file"
    exit 1
fi

set -- ""
while IFS= read -r entries; do
  set -- "$@" "$entries"
done <<EOF
$(sqlite3 "$sqlite_file" <<SQL
.mode list
SELECT * FROM urls;
.quit
SQL
)
EOF

shift

for entries do
  shortcode=$(echo "$entries" | cut -d '|' -f 1)
  url=$(echo "$entries" | cut -d '|' -f 2)
  title=$(echo "$entries" | cut -d '|' -f 3)

  make short url="$url" shortcode="$shortcode" title="$title"
done